service: segreti-frontend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

resources:
  Resources:
    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
              AllowedOrigins:
                - '*'
              MaxAge: 0
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - POST
                - DELETE
              AllowedOrigins:
                - 'https://*.amazonaws.com'
              MaxAge: 0

    FrontendBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FrontendBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.bucketName}/*

plugins:
  - serverless-s3-sync

custom:
  siteName: segreti
  bucketName: ${sls:stage}-${self:custom.siteName}
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: dist
